### ISSUE TITLE
'relation "public.paulg" does not exist'

### ISSUE THREAD

**Issue by abali96** [mckaywrigley/paul-graham-gpt#1]
Running `npm run embed` results in `relation "public.paulg" does not exist`. I believe line 31 of `embed.ts` needs to reference "pg" instead of "paulg".

https://github.com/mckaywrigley/paul-graham-gpt/blob/40a674e9ed274ef1dc3bedda8d6581a057467a25/scripts/embed.ts#L31

**Comment by mckaywrigley** [comment]
Just fixed it - thanks!

**Comment by abali96** [comment]
Sorry one more — seems like "paulg_search" should be replaced with "pg_search"

https://github.com/mckaywrigley/paul-graham-gpt/blob/89660f2b721a71be321d9d39bc3d1d6b3a206e1c/pages/api/search.ts#L32
