### ISSUE TITLE
Got a question for cosine similarity calculation

### ISSUE THREAD

**Issue by shao-shuai** [mckaywrigley/paul-graham-gpt#12]
```plpgsql
create or replace function pg_search (
  query_embedding vector(1536),
  similarity_threshold float,
  match_count int
)
returns table (
  id bigint,
  essay_title text,
  essay_url text,
  essay_date text,
  essay_thanks text,
  content text,
  content_length bigint,
  content_tokens bigint,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    pg.id,
    pg.essay_title,
    pg.essay_url,
    pg.essay_date,
    pg.essay_thanks,
    pg.content,
    pg.content_length,
    pg.content_tokens,
    1 - (pg.embedding <=> query_embedding) as similarity
  from pg
  where 1 - (pg.embedding <=> query_embedding) > similarity_threshold
  order by pg.embedding <=> query_embedding
  limit match_count;
end;
$$;


``` 

For this search function, since 1 - (zen_motor.embedding <=> query_embedding) expression does indeed return [cosine distance](https://stackoverflow.com/questions/58381092/difference-between-cosine-similarity-and-cosine-distance), where 0 indicates perfect similarity and 1 indicates perfect dissimilarity. So smaller number means more similar comparison, shouldn't we use `1 - (pg.embedding <=> query_embedding) < similarity_threshold` instead of `1 - (pg.embedding <=> query_embedding) > similarity_threshold` to get the most related content?

**Comment by mckaywrigley** [comment]
1 is actually perfect sim.
