### ISSUE TITLE
'relation "public.pg" does not exist'

### ISSUE THREAD

**Issue by emilepetrone** [mckaywrigley/paul-graham-gpt#3]
After creating a Supabase db and storing the creds in .env.local, when I run ` npm run embed`, I get the following error:

```
error {
  code: '42P01',
  details: null,
  hint: null,
  message: 'relation "public.pg" does not exist'
}
```

**Comment by mckaywrigley** [comment]
Can you confirm that a "pg" table was created in Supabase? Or is a table not creating at all? @emilepetrone

**Comment by emilepetrone** [comment]
@mckaywrigley Not getting created. Cloned again - confirmed

**Comment by emilepetrone** [comment]
@mckaywrigley Helps actually to run the DB migration in the editor.🤦‍♂️  Working now
